### ISSUE TITLE
Unicode decode errors handling command line arguments

### ISSUE THREAD

**Issue by eoyslebo** [log2timeline/plaso#351]
Running log2timeline.py on images containing non-ascii characters on the latest SIFT workstation gives me the above error message. Also tested on latest version pulled from github.

A quick google search took me to (http://stackoverflow.com/questions/22947181/dont-argparse-read-unicode-from-commandline) where a similar issue is discussed.

A search and replace for 5 instances of "type=unicode" with "type=lambda s: s.decode(sys.getfilesystemencoding())" in log2timeline.py appears to resolve the issue for me:

sed -ri 's/type=unicode/type=lambda s: s.decode(sys.getfilesystemencoding())/' log2timeline.py

**Comment by eoyslebo** [comment]
update: this workaround gets log2timeline.py running, but it later crashes on a related UTF issue

**Comment by Onager** [comment]
Where's the other unicode crash?

**Comment by eoyslebo** [comment]
running against all partitions on an image, it crashes after processing part of the first (recovery) partition:

[INFO] Data files will be loaded from /usr/share/plaso by default.

The following partitions were found:

Identifier	Offset (in bytes)	Size (in bytes)

p1		1048576 (0x00100000)	300.0MiB / 314.6MB (314572800 B)

p2		315621376 (0x12d00000)	100.0MiB / 104.9MB (104857600 B)

p3		420478976 (0x19100000)	128.0MiB / 134.2MB (134217728 B)

p4		554696704 (0x21100000)	468.6GiB / 503.2GB (503166533632 B)

p5		503721230336 (0x7548200000)	7.8GiB / 8.4GB (8388608000 B)



Please specify the identifier of the partition that should be processed.

All partitions can be defined as: "all". Note that you can abort with Ctrl^C.

all

The following Volume Shadow Snapshots (VSS) were found:

Identifier	VSS store identifier			Creation Time

vss1		2ee440fa-e845-11e4-8301-7824afbafe66	2015-04-22T03:24:06.208193+00:00

vss2		7717e33f-edce-11e4-8308-7824afbafe66	2015-04-30T21:23:07.824368+00:00

vss3		a2bb6e38-f4a1-11e4-8310-7824afbafe66	2015-05-08T09:34:28.785555+00:00



Please specify the identifier(s) of the VSS that should be processed:

Note that a range of stores can be defined as: 3..5. Multiple stores can

be defined as: 1,3,5 (a list of comma separated values). Ranges and lists can

also be combined as: 1,3..5. The first store is 1. All stores can be defined

as "all". If no stores are specified none will be processed. You

can abort with Ctrl^C.

all



Source path	: /mnt/images/øæå.dd

Source type	: storage media image



Processing started.

2015-10-01 15:49:39,788 [WARNING] (StorageWriter) PID:765 <multi_process> Unhandled exception in storage writer (PID: 765).

2015-10-01 15:49:39,788 [ERROR] (StorageWriter) PID:765 <multi_process> 'ascii' codec can't decode byte 0xc3 in position 90: ordinal not in range(128)

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/multi_process.py", line 1184, in _Main

    self._storage_writer.WriteEventObjects()

  File "/usr/lib/python2.7/dist-packages/plaso/lib/storage.py", line 1643, in WriteEventObjects

    self._Open()

  File "/usr/lib/python2.7/dist-packages/plaso/lib/storage.py", line 1685, in _Open

    serializer_format=self._serializer_format)

  File "/usr/lib/python2.7/dist-packages/plaso/lib/storage.py", line 255, in __init__

    self._Open(read_only)

  File "/usr/lib/python2.7/dist-packages/plaso/lib/storage.py", line 315, in _Open

    cmd_line = u' '.join(sys.argv)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 90: ordinal not in range(128)

2015-10-01 15:49:40,628 [WARNING] (Worker_01 ) PID:767 <text_parser> Unable to decode line ['d\x00\x01\x00\x00\x00\xe84m\xb3\x11E\xe4\x11\x9e\x14x$\xaf\xba\xfef\x00\x00\x00\x00\x00\x00\x00'...] with encoding: utf-8 in file: TSK:/$Extend/$RmMetadata/$TxfLog/$Tops

2015-10-01 15:49:40,632 [WARNING] (Worker_01 ) PID:767 <text_parser> Unable to decode line ['d\x00\x01\x00\x00\x00\xe84m\xb3\x11E\xe4\x11\x9e\x14x$\xaf\xba\xfef\x00\x00\x00\x00\x00\x00\x00'...] with encoding: UTF-8-SIG in file: TSK:/$Extend/$RmMetadata/$TxfLog/$Tops

2015-10-01 15:49:40,632 [WARNING] (Worker_01 ) PID:767 <text_parser> Unable to decode line ['d\x00\x01\x00\x00\x00\xe84m\xb3\x11E\xe4\x11\x9e\x14x$\xaf\xba\xfef\x00\x00\x00\x00\x00\x00\x00'...] with encoding: UTF-8 in file: TSK:/$Extend/$RmMetadata/$TxfLog/$Tops

2015-10-01 15:49:40,652 [WARNING] (Worker_01 ) PID:767 <text_parser> Unable to decode line ['d\x00\x01\x00\x00\x00\xe84m\xb3\x11E\xe4\x11\x9e\x14x$\xaf\xba\xfef\x00\x00\x00\x00\x00\x00\x00'...] with encoding: utf-8 in file: TSK:/$Extend/$RmMetadata/$TxfLog/$Tops

2015-10-01 15:49:40,653 [WARNING] (Worker_01 ) PID:767 <text_parser> Unable to decode line ['d\x00\x01\x00\x00\x00\xe84m\xb3\x11E\xe4\x11\x9e\x14x$\xaf\xba\xfef\x00\x00\x00\x00\x00\x00\x00'...] with encoding: UTF-8 in file: TSK:/$Extend/$RmMetadata/$TxfLog/$Tops

2015-10-01 15:49:40,653 [WARNING] (Worker_01 ) PID:767 <text_parser> Unable to decode line ['d\x00\x01\x00\x00\x00\xe84m\xb3\x11E\xe4\x11\x9e\x14x$\xaf\xba\xfef\x00\x00\x00\x00\x00\x00\x00'...] with encoding: utf-8 in file: TSK:/$Extend/$RmMetadata/$TxfLog/$Tops

/usr/lib/python2.7/dist-packages/pyparsing.py:1593: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal

  if (instring[loc] == self.firstMatchChar and

Worker_00 (PID: 766) - events extracted: 250 - file: TSK:/EFI/Microsoft/Boot/pt-BR/bootmgfw.efi.mui - running: True <running>

Worker_01 (PID: 767) - events extracted: 383 - file: TSK:/EFI/Microsoft/Boot/pt-BR/bootmgr.efi.mui - running: True <running>

2015-10-01 15:49:42,905 [ERROR] (MainProcess) PID:760 <multi_process> Process StorageWriter (PID: 765) is not functioning correctly.

2015-10-01 15:49:42,905 [WARNING] (MainProcess) PID:760 <multi_process> Processing aborted with engine error: Storage writer unexpectedly terminated.

2015-10-01 15:49:42,905 [WARNING] (MainProcess) PID:760 <multi_process> Terminating process: Collector (PID: 769).

2015-10-01 15:49:42,905 [WARNING] (MainProcess) PID:760 <multi_process> Terminating process: Worker_00 (PID: 766).

2015-10-01 15:49:42,905 [WARNING] (MainProcess) PID:760 <multi_process> Terminating process: Worker_01 (PID: 767).

2015-10-01 15:49:47,911 [WARNING] (MainProcess) PID:760 <multi_process> Killing process: Collector (PID: 769).

Processing completed with errors.

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/blob/master/plaso/lib/storage.py#L315

args handling should not be done inside storage, see [separation of concerns](https://en.wikipedia.org/wiki/Separation_of_concerns)

**Comment by joachimmetz** [comment]
Also what are you terminal/console encoding settings?
```
echo $LANG
```

**Comment by eoyslebo** [comment]
$echo $LANG:
nb_NO.UTF-8

**Comment by Onager** [comment]
I can reproduce on Ubuntu, trying to run log2timeline.py on the ímynd.dd file from test_data. $LANG=en_US.UTF-8

**Comment by joachimmetz** [comment]
argparse related issue:
```
log2timeline.py: error: argument SOURCE: invalid unicode value: 'test_data/\xc3\xadmynd.dd'
```

**Comment by joachimmetz** [comment]
Work-around pending in: https://codereview.appspot.com/264640043/

**Comment by joachimmetz** [comment]
Should be fixed now. Closing issue, reopen if there are still issues.

**Comment by eoyslebo** [comment]
On a clean trusty install I still get a UTF-related error: 

vagrant@vagrant-ubuntu-trusty-64:~$ log2timeline.py /tmp/out2.dump "/vagrant/øæå.E01"
[INFO] Data files will be loaded from /usr/local/lib/python2.7/dist-packages/plaso-1.3.1_20151011-py2.7.egg/share/plaso by default.
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 5, in <module>
    pkg_resources.run_script('plaso==1.3.1-20151011', u'log2timeline.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.1_20151011-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 750, in <module>
    if not Main():
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.1_20151011-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 709, in Main
    if not tool.ParseArguments():
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.1_20151011-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 540, in ParseArguments
    self._command_line_arguments = u' '.join(command_line_arguments)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)

**Comment by joachimmetz** [comment]
Hmm, looking at https://github.com/log2timeline/plaso/blob/master/tools/log2timeline.py#L534 there is a bug there.

**Comment by joachimmetz** [comment]
Adding fix to https://codereview.appspot.com/267200043/ since that CL also fixes the same issue for psort.

**Comment by eoyslebo** [comment]
vagrant@vagrant-ubuntu-trusty-64:~$ log2timeline.py -V;log2timeline.py out.dump /vagrant/øæå.E01 
plaso - log2timeline version 1.3.1_20151013
[INFO] Data files will be loaded from /usr/local/lib/python2.7/dist-packages/plaso-1.3.1_20151013-py2.7.egg/share/plaso by default.
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 5, in <module>
    pkg_resources.run_script('plaso==1.3.1-20151013', u'log2timeline.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.1_20151013-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 740, in <module>
    if not Main():
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.1_20151013-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 699, in Main
    if not tool.ParseArguments():
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.1_20151013-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 530, in ParseArguments
    self._command_line_arguments = self.GetCommandLineArguments()
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.1_20151013-py2.7.egg/plaso/cli/tools.py", line 275, in GetCommandLineArguments
    return u' '.join(command_line_arguments)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)

**Comment by joachimmetz** [comment]
Thanks for the reminder but seeing last [PR](https://github.com/joachimmetz/plaso/commit/26ead1a8f077326b4b1030064675b1fabf760209) has not been merged yet, this is as expected.

**Comment by joachimmetz** [comment]
@eoyslebo I opt to try again with latest version of HEAD

**Comment by eoyslebo** [comment]
No error messages/issues now. 

Thank you.

**Comment by bf** [comment]
Unfortunately the startup issue is not fixed for me when using the current docker image with log2timeline version 1.4.0:

I could provide a list of files and directories for reproduction purposes.

```
Processing started.
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 816, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 802, in Main
    tool.ProcessSources()
  File "/usr/bin/log2timeline.py", line 735, in ProcessSources
    timezone=self._timezone)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/extraction_frontend.py", line 471, in ProcessSources
    pre_obj = self._PreprocessSources(source_path_specs, source_type)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/extraction_frontend.py", line 191, in _PreprocessSources
    source_path_specs, resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/engine.py", line 103, in PreprocessSources
    platform = preprocess_interface.GuessOS(searcher)
  File "/usr/lib/python2.7/dist-packages/plaso/preprocessors/interface.py", line 203, in GuessOS
    for path_spec in searcher.Find(find_specs=find_specs):
  File "/usr/lib/python2.7/dist-packages/dfvfs/helpers/file_system_searcher.py", line 410, in Find
    for matching_path_spec in self._FindInFileEntry(file_entry, find_specs, 0):
  File "/usr/lib/python2.7/dist-packages/dfvfs/helpers/file_system_searcher.py", line 379, in _FindInFileEntry
    for sub_file_entry in file_entry.sub_file_entries:
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/os_file_entry.py", line 228, in sub_file_entries
    for path_spec in self._directory.entries:
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/file_entry.py", line 67, in entries
    for entry in self._EntriesGenerator():
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/os_file_entry.py", line 45, in _EntriesGenerator
    location, directory_entry])
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/os_file_system.py", line 191, in JoinPath
    segment.split(self.PATH_SEPARATOR) for segment in path_segments]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)
```

I also get an utf8 error when just including `/xyz/øæå.d` as file name parameter.

```
docker run -v /data:/data -v /run/media/targetdir:/drive e687ba2cd049 log2timeline.py /data/l2t.dump /drive --parsers "winevtx,lnk,winreg,webhist,skype,winxp,win7" --workers 6  --version
> plaso - log2timeline version 1.4.0
```
