### ISSUE TITLE
OSX install error

### ISSUE THREAD

**Issue by regaindata** [log2timeline/plaso#559]
I received the following error when executing install.sh of the latest plaso 1.4. I have no issues with the RC3 version of 1.4. I see the code is different between the 2. 

===============================================================
               Plaso Mac OS-X installation script
===============================================================

./install.sh: line 31: syntax error near unexpected token `do'

./install.sh: line 31: `do'

**Comment by Onager** [comment]
This is https://github.com/log2timeline/plaso/issues/554 

It's fixed in HEAD Plaso.

**Comment by regaindata** [comment]
I see the fix. Thanks

**Comment by joachimmetz** [comment]
Can you check the current Mac OS X build of https://github.com/log2timeline/plaso/releases/tag/1.4.0 this should be fixed there. I might have not updated one on Google drive yet.

**Comment by eugk** [comment]
FYI, still broken in the DMG here: https://e366e647f8637dd31e0a13f75e5469341a9ab0ee.googledrive.com/host/0B30H7z4S52FleW5vUHBnblJfcjg/1.4.0/
